### ISSUE TITLE
Error in neovim E118: Too many arguments for function: <SNR>138_callback_exit

### ISSUE THREAD

**Issue by duikboot** [mhinz/vim-signify#204]
When starting neovim I get this error five thimes:
E118: Too many arguments for function: <SNR>138_callback_exit

I don't get these error messages when in uninstall vim-signify.

$ nvim -v
NVIM v0.2.0-458-g7255f00
Build type: RelWithDebInfo

I hope you have enough information.

Thanks for your plugin, I really love it

**Comment by mhinz** [comment]
Apparently I missed to test this with Neovim master. It should have worked with the latest Neovim release v01.7.

Anyway, it's fixed now. Thanks for reporting this!

**Comment by mhinz** [comment]
@duikboot By the way, if you got that error 5 times, it means that Sy found 5 supported version control tools installed and tests for all of them (asynchronously but still) for each new file.

If you usually just use `git` and `hg` for example, consider setting `:h g:signify_vcs_list`.

**Comment by duikboot** [comment]
> If you usually just use git and hg for example, consider setting :h g:signify_vcs_list.

Thanks for the tip and your quick response.
