### ISSUE TITLE
Error in neovim: E118: Too many arguments for function: haslocaldir

### ISSUE THREAD

**Issue by platosha** [mhinz/vim-signify#197]
I’ve got these error messages:

```
Error detected while processing function sy#start..<SNR>309_chdir:
line    2:
E118: Too many arguments for function: haslocaldir
E15: Invalid expression: haslocaldir() ? 'lcd' : haslocaldir(-1, 0) ? 'tcd' : 'cd'
Error detected while processing function sy#start..sy#repo#detect..sy#repo#get_diff_git..<SNR>311_run:
line    1:
E486: Pattern not found: Users
line    9:
E486: Pattern not found: Users
Error detected while processing function sy#start..sy#repo#detect:
line   13:
E170: Missing :endfor
Error detected while processing function sy#start:
line   50:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..75..74..<SNR>170_activateFileNode..103..120..174:
line    4:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..75..74:
line    3:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap..75:
line   18:
E171: Missing :endif
```

I am using neovim installed with Homebrew on OS X:
```
➜  ~ nvim -v
NVIM v0.1.0-4-g4196d0b (compiled Nov  4 2015 11:39:51)
Commit: 4196d0b983d56ac598a30f955bca6d941b058046
Build type: Dev
```

Most probably introduced in https://github.com/mhinz/vim-signify/pull/192. Reverting that change fixes the error.

**Comment by jamessan** [comment]
Can you update to a Neovim that's less than a year old?

**Comment by platosha** [comment]
@jamessan yep, the error is gone. Thanks, sorry for disturbing.
